import type { CategoryMeta, ToolEntry } from "./types";

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "pretend",
    label: "일하는 척",
    emoji: "😎",
    href: "/pretend",
    title: "일하는 척",
    description:
      "멀리서 보면 완벽한 업무 화면. 개발, 엑셀, 터미널, 대시보드까지 전체화면으로 실행됩니다.",
  },
  {
    id: "tools",
    label: "업무도구",
    emoji: "🛠",
    href: "/tools",
    title: "업무도구",
    description:
      "설치도 로그인도 없이 바로 쓰는 계산기, 날짜·시간 계산, 글자수 세기 같은 실무 도구.",
  },
  {
    id: "ai",
    label: "AI",
    emoji: "🤖",
    href: "/ai",
    title: "AI 도구",
    description:
      "번역, 요약, 이메일 작성처럼 반복되는 업무를 대신 처리할 AI 도구를 준비하고 있습니다.",
  },
  {
    id: "fun",
    label: "쉬어가기",
    emoji: "😴",
    href: "/fun",
    title: "잠깐 쉬어가기",
    description: "퇴근까지 남은 시간을 확인하고, 잠깐 머리를 식히는 가벼운 게임.",
  },
];

/**
 * Single source of truth for every tool on the site: navigation, category
 * pages, the home page sections, search and the sitemap all read from here.
 *
 * Adding a feature = adding an entry here + a route. Nothing else to update.
 */
export const TOOLS: ToolEntry[] = [
  // ── 😎 일하는 척 ────────────────────────────────────────────────
  {
    id: "vscode",
    name: "VS Code",
    category: "pretend",
    href: "/pretend/vscode",
    description: "코드가 저절로 써지는 개발자 화면. 파일 탐색기와 탭까지 그대로.",
    icon: "code",
    status: "live",
    enabled: true,
    keywords: ["vscode", "코딩", "개발", "개발자 화면", "코딩 화면", "editor", "ide"],
    order: 1,
  },
  {
    id: "excel",
    name: "Excel",
    category: "pretend",
    href: "/pretend/excel",
    description: "실적표를 들여다보는 중. 셀 편집과 수식 입력줄까지 동작합니다.",
    icon: "table",
    status: "live",
    enabled: true,
    keywords: ["엑셀", "excel", "스프레드시트", "spreadsheet", "표", "시트"],
    order: 2,
  },
  {
    id: "terminal",
    name: "Terminal",
    category: "pretend",
    href: "/pretend/terminal",
    description: "배포 로그가 끝없이 흐르는 검은 화면. 명령어도 입력할 수 있습니다.",
    icon: "terminal",
    status: "live",
    enabled: true,
    keywords: ["터미널", "terminal", "cli", "shell", "배포", "deploy", "로그"],
    order: 3,
  },
  {
    id: "dashboard",
    name: "Business Dashboard",
    category: "pretend",
    href: "/pretend/dashboard",
    description: "매출·전환율이 실시간으로 움직이는 경영 대시보드.",
    icon: "chart",
    status: "live",
    enabled: true,
    keywords: ["대시보드", "dashboard", "매출", "지표", "kpi", "리포트", "analytics"],
    order: 4,
  },
  {
    id: "sql",
    name: "SQL Client",
    category: "pretend",
    href: "/pretend/sql",
    description: "쿼리를 돌리는 중인 DB 클라이언트 화면.",
    icon: "database",
    status: "soon",
    enabled: false,
    keywords: ["sql", "쿼리", "데이터베이스", "db", "mysql"],
    order: 5,
  },
  {
    id: "git",
    name: "Git History",
    category: "pretend",
    href: "/pretend/git",
    description: "커밋 그래프와 diff가 흐르는 형상관리 화면.",
    icon: "git",
    status: "soon",
    enabled: false,
    keywords: ["git", "깃", "커밋", "commit", "diff", "형상관리"],
    order: 6,
  },
  {
    id: "server-monitor",
    name: "Server Monitor",
    category: "pretend",
    href: "/pretend/server-monitor",
    description: "CPU·메모리 그래프가 살아 움직이는 서버 모니터링.",
    icon: "server",
    status: "soon",
    enabled: false,
    keywords: ["서버", "모니터링", "server", "monitor", "cpu", "인프라"],
    order: 7,
  },

  // ── 🛠 업무도구 ─────────────────────────────────────────────────
  {
    id: "calculator",
    name: "계산기",
    category: "tools",
    href: "/tools/calculator",
    description: "키보드로 바로 두드리는 계산기. 모바일에서도 넉넉한 버튼.",
    icon: "calculator",
    status: "live",
    enabled: true,
    keywords: ["계산기", "calculator", "사칙연산", "퍼센트", "%", "계산"],
    order: 1,
  },
  {
    id: "date-calculator",
    name: "날짜 계산기",
    category: "tools",
    href: "/tools/date-calculator",
    description: "날짜 차이, D-Day, 며칠 뒤·며칠 전을 한 화면에서.",
    icon: "calendar",
    status: "live",
    enabled: true,
    keywords: ["날짜 계산기", "디데이", "d-day", "날짜 차이", "date", "기념일", "영업일"],
    order: 2,
  },
  {
    id: "time-calculator",
    name: "시간 계산기",
    category: "tools",
    href: "/tools/time-calculator",
    description: "근무시간 정산, 시간 차이, 시간 더하기·빼기.",
    icon: "clock",
    status: "live",
    enabled: true,
    keywords: ["시간 계산기", "근무시간", "출퇴근", "time", "야근", "휴게시간"],
    order: 3,
  },
  {
    id: "character-counter",
    name: "글자수 세기",
    category: "tools",
    href: "/tools/character-counter",
    description: "공백 포함·제외 글자수, 단어수, 줄수를 실시간으로.",
    icon: "text",
    status: "live",
    enabled: true,
    keywords: ["글자수", "글자수 세기", "자소서", "단어수", "character counter", "바이트"],
    order: 4,
  },
  {
    id: "json-formatter",
    name: "JSON 정리",
    category: "tools",
    href: "/tools/json-formatter",
    description: "엉킨 JSON을 읽기 좋게 정렬하고 검증합니다.",
    icon: "braces",
    status: "soon",
    enabled: false,
    keywords: ["json", "포맷터", "formatter", "정렬", "validator"],
    order: 5,
  },
  {
    id: "unit-converter",
    name: "단위 변환",
    category: "tools",
    href: "/tools/unit-converter",
    description: "길이·무게·넓이·온도 단위를 한 번에 변환.",
    icon: "swap",
    status: "soon",
    enabled: false,
    keywords: ["단위 변환", "unit", "converter", "평", "인치", "kg"],
    order: 6,
  },
  {
    id: "salary-calculator",
    name: "실수령액 계산기",
    category: "tools",
    href: "/tools/salary-calculator",
    description: "연봉에서 4대보험과 세금을 뺀 실수령액.",
    icon: "wallet",
    status: "soon",
    enabled: false,
    keywords: ["연봉", "실수령액", "월급", "세후", "salary", "4대보험"],
    order: 7,
  },
  {
    id: "qr-generator",
    name: "QR 코드 생성",
    category: "tools",
    href: "/tools/qr-generator",
    description: "링크나 텍스트를 QR 코드 이미지로.",
    icon: "qr",
    status: "soon",
    enabled: false,
    keywords: ["qr", "큐알", "qr코드", "generator"],
    order: 8,
  },

  // ── 🤖 AI ──────────────────────────────────────────────────────
  {
    id: "ai-translate",
    name: "AI 번역",
    category: "ai",
    href: "/ai/translate",
    description: "업무 메일 톤을 유지한 채 번역합니다.",
    icon: "translate",
    status: "soon",
    enabled: false,
    keywords: ["ai 번역", "번역", "translate", "영어", "비즈니스 영어"],
    order: 1,
  },
  {
    id: "ai-summarize",
    name: "AI 문서 요약",
    category: "ai",
    href: "/ai/summarize",
    description: "긴 문서와 회의록을 핵심만 남겨 정리합니다.",
    icon: "sparkles",
    status: "soon",
    enabled: false,
    keywords: ["ai 요약", "요약", "summary", "문서", "회의록"],
    order: 2,
  },
  {
    id: "ai-email",
    name: "AI 이메일 작성",
    category: "ai",
    href: "/ai/email",
    description: "상황만 적으면 보낼 수 있는 메일이 됩니다.",
    icon: "mail",
    status: "soon",
    enabled: false,
    keywords: ["ai 이메일", "메일 작성", "email", "답장", "비즈니스 메일"],
    order: 3,
  },
  {
    id: "ai-report",
    name: "AI 보고서 작성",
    category: "ai",
    href: "/ai/report",
    description: "몇 줄의 메모를 보고서 형식으로 확장합니다.",
    icon: "document",
    status: "soon",
    enabled: false,
    keywords: ["ai 보고서", "보고서", "report", "기획서", "주간보고"],
    order: 4,
  },
  {
    id: "ai-excel-formula",
    name: "AI 엑셀 함수",
    category: "ai",
    href: "/ai/excel-formula",
    description: "원하는 계산을 말하면 엑셀 수식으로 바꿔줍니다.",
    icon: "function",
    status: "soon",
    enabled: false,
    keywords: ["엑셀 함수", "엑셀 수식", "vlookup", "formula", "ai 엑셀"],
    order: 5,
  },

  // ── 😴 쉬어가기 ────────────────────────────────────────────────
  {
    id: "quit-countdown",
    name: "퇴근 카운트다운",
    category: "fun",
    href: "/fun/quit-countdown",
    description: "퇴근까지 남은 시간과 오늘의 근무 진행률.",
    icon: "timer",
    status: "live",
    enabled: true,
    keywords: ["퇴근", "퇴근 카운트다운", "퇴근시간", "칼퇴", "남은 시간", "countdown"],
    order: 1,
  },
  {
    id: "2048",
    name: "2048",
    category: "fun",
    href: "/fun/2048",
    description: "설치도 로그인도 없이 바로 시작하는 2048.",
    icon: "game",
    status: "live",
    enabled: true,
    keywords: ["2048", "게임", "퍼즐", "시간때우기", "game", "puzzle"],
    order: 2,
  },
  {
    id: "minesweeper",
    name: "지뢰찾기",
    category: "fun",
    href: "/fun/minesweeper",
    description: "그 시절 그 지뢰찾기.",
    icon: "flag",
    status: "soon",
    enabled: false,
    keywords: ["지뢰찾기", "minesweeper", "게임"],
    order: 3,
  },
  {
    id: "reaction-test",
    name: "반응속도 테스트",
    category: "fun",
    href: "/fun/reaction-test",
    description: "지금 내 정신이 붙어 있는지 확인하는 시간.",
    icon: "bolt",
    status: "soon",
    enabled: false,
    keywords: ["반응속도", "reaction", "테스트", "게임"],
    order: 4,
  },
  {
    id: "fortune",
    name: "오늘의 운세",
    category: "fun",
    href: "/fun/fortune",
    description: "오늘 이 회의를 버틸 수 있을지 물어보세요.",
    icon: "star",
    status: "soon",
    enabled: false,
    keywords: ["운세", "오늘의 운세", "fortune", "타로", "심리테스트"],
    order: 5,
  },
];
